### ISSUE TITLE
class file for com.squareup.wire.Message not found

### ISSUE THREAD

**Issue by kaustav07** [simonpercic/ResponseEcho#18]
I forked your library to Host in my own server, but I cant get it ti run. I tried to run it with IntelliJ but had to upgrade gradle wrapper to 6.0.1 and spring boot framework to 2.2.2 , but after resolving the gradle issues I cant get it to run  and it gives this error 'class file for com.squareup.wire.Message not found', can you help?

**Comment by simonpercic** [comment]
Resolved in #22
